version: "3.8"

services:
  app:
    build: .
    container_name: livros-api
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - DATABASE_URL=sqlite:///./livros.db
      - MEU_USUARIO=admin
      - MINHA_SENHA=admin
    command: ["poetry", "run", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
