[tool.poetry]
name = "backend-livros-ebac-python"
version = "0.1.0"
description = ""
authors = ["Atilio <atilio.jesus@grupoboticario.com.br>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
fastapi = {extras = ["standard"], version = "^0.115.6"}


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
