name: FastAPI - Basic Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  fastapi-docker-test:
    runs-on: ubuntu-latest

    steps:
      - name: 🔄 Checkout do código
        uses: actions/checkout@v3

      - name: 🐳 Build da imagem Docker
        run: docker build -t my-fastapi-app .
